#!/usr/bin/env bash
set -euo pipefail

SCRIPT_VERSION="v1.1.0"

PROJECT_PATH=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -p) PROJECT_PATH="${2:-}"; shift 2 ;;
    --version) echo "precommit_uninstall.sh $SCRIPT_VERSION"; exit 0 ;;
    *) echo "Unknown parameter: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "${PROJECT_PATH}" ]]; then PROJECT_PATH="$(pwd)"; fi
if [[ ! -d "$PROJECT_PATH" ]]; then echo "❌ Project path not found: $PROJECT_PATH" >&2; exit 2; fi

HOOKS_PATH="$(git -C "$PROJECT_PATH" config --get core.hooksPath || true)"
if [[ -z "${HOOKS_PATH}" ]]; then
  HOOKS_PATH="$PROJECT_PATH/.git/hooks"
fi
HOOK_FILE="$HOOKS_PATH/pre-commit"

if [[ -f "$HOOK_FILE" ]]; then
  if grep -q "pre-commit generated by precommit_install.sh v1.1.0" "$HOOK_FILE"; then
    rm -f "$HOOK_FILE"
    echo "✅ Removed pre-commit hook: $HOOK_FILE"
  else
    echo "⚠️  pre-commit hook not installed by this installer, leaving it untouched: $HOOK_FILE"
  fi
else
  echo "ℹ️  No pre-commit hook found at: $HOOK_FILE"
fi
